/**
 * Schéma SQL complet, généré depuis la base de développement.
 * Sert au démarrage (voir ./bootstrap.ts) à créer les tables dans une base
 * vide — cas d'un nouveau déploiement où le fichier SQLite n'existe pas encore.
 * À régénérer après toute modification de ./schema.ts :
 *   bun run packages/web/src/api/database/generate-ddl.ts
 */
export const SCHEMA_DDL: readonly string[] = [
  "CREATE TABLE IF NOT EXISTS `account` ( `id` text PRIMARY KEY NOT NULL, `account_id` text NOT NULL, `provider_id` text NOT NULL, `user_id` text NOT NULL, `access_token` text, `refresh_token` text, `id_token` text, `access_token_expires_at` integer, `refresh_token_expires_at` integer, `scope` text, `password` text, `created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL, `updated_at` integer NOT NULL, FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `api_keys` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `label` text NOT NULL, `key` text NOT NULL, `revoked` integer DEFAULT false NOT NULL, `last_used_at` integer, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `audit_log` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `user_id` text, `user_email` text, `action` text NOT NULL, `target` text, `detail` text, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `carrier_applications` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `email` text NOT NULL, `phone` text NOT NULL, `city` text NOT NULL, `vehicle` text NOT NULL, `capacity_m3` real, `siret` text, `message` text, `status` text DEFAULT 'nouveau' NOT NULL, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `chat_leads` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text, `phone` text, `email` text, `topic` text DEFAULT 'general' NOT NULL, `transcript` text, `channel` text DEFAULT 'site_chat' NOT NULL, `locale` text DEFAULT 'fr' NOT NULL, `handled` integer DEFAULT false NOT NULL, `forwarded_at` integer, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `contacts` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `email` text NOT NULL, `phone` text, `subject` text NOT NULL, `message` text NOT NULL, `handled` integer DEFAULT false NOT NULL, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `driver_jobs` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `driver_id` integer NOT NULL, `tracking_number` text NOT NULL, `pickup_address` text NOT NULL, `drop_address` text NOT NULL, `recipient_name` text, `recipient_phone` text, `scheduled_at` integer, `status` text DEFAULT 'a_recuperer' NOT NULL, `payout_cents` integer, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `drivers` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `email` text NOT NULL, `phone` text, `code` text NOT NULL, `vehicle` text, `city` text, `active` integer DEFAULT true NOT NULL, `created_at` integer NOT NULL , `first_name` text, `last_name` text, `whatsapp` text, `address` text, `plate` text, `siret` text, `password_hash` text, `license_key` text, `id_photo_key` text, `vehicle_doc_key` text, `email_verified` integer DEFAULT false NOT NULL, `verify_code` text, `verify_expires_at` integer, `reset_token` text, `reset_expires_at` integer, `approval_status` text DEFAULT 'valide' NOT NULL, `approval_note` text, `approved_at` integer, `available` integer DEFAULT false NOT NULL, `available_since` integer, `last_login_at` integer)",
  "CREATE TABLE IF NOT EXISTS `invoice_items` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `invoice_id` integer NOT NULL, `label` text NOT NULL, `detail` text, `quantity` real DEFAULT 1 NOT NULL, `unit` text DEFAULT 'forfait' NOT NULL, `unit_price_cents` integer DEFAULT 0 NOT NULL, `total_cents` integer DEFAULT 0 NOT NULL, `position` integer DEFAULT 0 NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `invoices` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `number` text NOT NULL, `quote_ref` text, `user_id` text, `customer_name` text NOT NULL, `customer_email` text NOT NULL, `customer_phone` text, `customer_company` text, `customer_address` text, `subject` text DEFAULT 'Prestation de transport' NOT NULL, `subtotal_cents` integer DEFAULT 0 NOT NULL, `vat_rate` real DEFAULT 20 NOT NULL, `vat_cents` integer DEFAULT 0 NOT NULL, `total_cents` integer DEFAULT 0 NOT NULL, `currency` text DEFAULT 'EUR' NOT NULL, `status` text DEFAULT 'en_attente_paiement' NOT NULL, `payment_method` text, `payment_reference` text, `paid_at` integer, `due_at` integer, `notes` text, `locale` text DEFAULT 'fr' NOT NULL, `created_at` integer NOT NULL, `updated_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `job_offers` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `tracking_number` text NOT NULL, `quote_ref` text, `service` text, `kind` text, `pickup_address` text NOT NULL, `drop_address` text NOT NULL, `recipient_name` text, `recipient_phone` text, `weight_kg` real, `volume_m3` real, `payout_cents` integer, `scheduled_at` integer, `status` text DEFAULT 'ouverte' NOT NULL, `accepted_driver_id` integer, `accepted_at` integer, `notified_count` integer DEFAULT 0 NOT NULL, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `newsletter_subscribers` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `email` text NOT NULL, `name` text, `source` text DEFAULT 'popup' NOT NULL, `locale` text DEFAULT 'fr' NOT NULL, `active` integer DEFAULT true NOT NULL, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payments` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `quote_ref` text NOT NULL, `provider` text DEFAULT 'virement' NOT NULL, `amount_cents` integer NOT NULL, `status` text DEFAULT 'en_attente' NOT NULL, `reference` text, `payer_email` text, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `quotes` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `ref` text NOT NULL, `kind` text DEFAULT 'colis' NOT NULL, `service` text DEFAULT 'standard' NOT NULL, `zone` text DEFAULT 'france' NOT NULL, `customer_name` text NOT NULL, `customer_email` text NOT NULL, `customer_phone` text, `company` text, `from_address` text NOT NULL, `to_address` text NOT NULL, `weight_kg` real, `length_cm` real, `width_cm` real, `height_cm` real, `volume_m3` real, `pieces` integer DEFAULT 1, `floors` integer DEFAULT 0, `elevator` integer DEFAULT false, `insurance` integer DEFAULT false, `home_pickup` integer DEFAULT false, `packing` integer DEFAULT false, `fragile` integer DEFAULT false, `declared_value` real, `goods_description` text, `message` text, `price_cents` integer NOT NULL, `breakdown` text, `eta_min` integer, `eta_max` integer, `status` text DEFAULT 'nouveau' NOT NULL, `tracking_number` text, `user_id` text, `invoice_id` integer, `decision` text, `decision_reason` text, `decided_at` integer, `locale` text DEFAULT 'fr' NOT NULL, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `session` ( `id` text PRIMARY KEY NOT NULL, `expires_at` integer NOT NULL, `token` text NOT NULL, `created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL, `updated_at` integer NOT NULL, `ip_address` text, `user_agent` text, `user_id` text NOT NULL, FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `site_settings` ( `key` text PRIMARY KEY NOT NULL, `value` text NOT NULL, `group` text DEFAULT 'general' NOT NULL, `label` text, `updated_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `tracking_events` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `tracking_number` text NOT NULL, `status` text NOT NULL, `label_fr` text NOT NULL, `label_en` text NOT NULL, `location` text, `occurred_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `tracking_locations` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `tracking_number` text NOT NULL, `driver_id` integer, `lat` real NOT NULL, `lng` real NOT NULL, `accuracy` real, `created_at` integer NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `trackings` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `tracking_number` text NOT NULL, `quote_id` integer, `recipient_name` text, `origin` text NOT NULL, `destination` text NOT NULL, `status` text DEFAULT 'cree' NOT NULL, `service` text DEFAULT 'standard' NOT NULL, `carrier` text DEFAULT 'LBG Express' NOT NULL, `external_carrier` text, `weight_kg` real, `eta` integer, `driver_id` integer, `source` text DEFAULT 'site' NOT NULL, `created_at` integer NOT NULL, `updated_at` integer NOT NULL , `review_requested_at` integer)",
  "CREATE TABLE IF NOT EXISTS `user` ( `id` text PRIMARY KEY NOT NULL, `name` text NOT NULL, `email` text NOT NULL, `email_verified` integer DEFAULT false NOT NULL, `image` text, `created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL, `updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL, `role` text DEFAULT 'client', `account_status` text DEFAULT 'actif', `phone` text, `company` text, `must_change_password` integer DEFAULT false )",
  "CREATE TABLE IF NOT EXISTS `verification` ( `id` text PRIMARY KEY NOT NULL, `identifier` text NOT NULL, `value` text NOT NULL, `expires_at` integer NOT NULL, `created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL, `updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `webhooks` ( `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `url` text NOT NULL, `secret` text NOT NULL, `events` text DEFAULT 'tracking.updated' NOT NULL, `active` integer DEFAULT true NOT NULL, `last_status` text, `created_at` integer NOT NULL )",
  "CREATE INDEX IF NOT EXISTS `account_userId_idx` ON `account` (`user_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `api_keys_key_unique` ON `api_keys` (`key`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `drivers_email_unique` ON `drivers` (`email`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `invoices_number_unique` ON `invoices` (`number`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `job_offers_tracking_number_unique` ON `job_offers` (`tracking_number`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `newsletter_subscribers_email_unique` ON `newsletter_subscribers` (`email`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `quotes_ref_unique` ON `quotes` (`ref`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `session_token_unique` ON `session` (`token`)",
  "CREATE INDEX IF NOT EXISTS `session_userId_idx` ON `session` (`user_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `trackings_tracking_number_unique` ON `trackings` (`tracking_number`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `user_email_unique` ON `user` (`email`)",
  "CREATE INDEX IF NOT EXISTS `verification_identifier_idx` ON `verification` (`identifier`)",
];
